se3_hopf_node:
  ros__parameters:
    px4_namespace: "/fmu/"
    control_mode: "attitude"
    enable_auto_offboard: true
    enable_auto_arm: true
    auto_takeoff: true
    require_imu_for_control: true
    publish_reference_topics: true
    # velocity_in_body: true
    offboard_warmup_count: 20
    request_interval: 1.0
    takeoff_height: 2.0
    hover_percent: 0.25
    max_hover_percent: 0.75
    tracking_warn_pos_threshold: 0.8
    tracking_warn_vel_threshold: 1.0
    control_warn_bodyrate_threshold: 4.0
    control_warn_thrust_delta_threshold: 0.35
    sample_sync_warn_ms: 20.0
    odom_imu_quat_warn_deg: 8.0

    geo_fence.x: 80.0
    geo_fence.y: 80.0
    geo_fence.z: 7.0

    kp_px: 0.85
    kp_py: 0.85
    kp_pz: 1.5

    kp_vx: 1.5
    kp_vy: 1.5
    kp_vz: 1.5

    kp_ax: 1.5
    kp_ay: 1.5
    kp_az: 1.5

    kp_qx: 5.5
    kp_qy: 5.5
    kp_qz: 0.1

    kp_wx: 1.5
    kp_wy: 1.5
    kp_wz: 0.1

    kd_px: 0.1
    kd_py: 0.1
    kd_pz: 0.0

    kd_vx: 0.0
    kd_vy: 0.0
    kd_vz: 0.0

    kd_ax: 0.0
    kd_ay: 0.0
    kd_az: 0.0

    kd_qx: 0.0
    kd_qy: 0.0
    kd_qz: 0.0

    kd_wx: 0.0
    kd_wy: 0.0
    kd_wz: 0.0

    limit_err_p: 3.0
    limit_err_v: 2.0
    limit_err_a: 1.0

    limit_d_err_p: 3.5
    limit_d_err_v: 1.0
    limit_d_err_a: 1.0
